apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
  - image: juliocesarjcrs/ticketing-auth
    context: auth
    docker:
      dockerfile: Dockerfile
  - image: juliocesarjcrs/ticketing-client
    context: client
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - ./infra/k8s/*
